add_newline = false
scan_timeout = 10
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$jobs\
$status\
$character"""

[status]
disabled = false
format = "[$status]($style) "

[jobs]
symbol = "jobs"
format = "[$number $symbol]($style)"

[git_branch]
symbol = "branch "
ignore_branches = ["main", "master"]

[directory]
truncation_length = 10
